name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Esegui ogni giorno a mezzanotte
  workflow_dispatch:     # Permette l'esecuzione manuale
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v2
        with:
          github_user_name: VaglioFabiano
          svg_output_path: assets/github-contribution-grid-snake.svg
      - uses: EndBug/add-and-commit@v9
        with:
          branch: main
          path: assets